version: "3.8"

volumes:
  rabbitmq_data:

services:
  ###################################
  # CRS: Central Reservation System microservice
  ###################################
  central_reservation_system:
    build:
      context: ./
      dockerfile: central_reservation_system.Dockerfile
    image: wenhai87/central_reservation_system:esd
    restart: always
    depends_on: 
      # - payment
      - inventory
      - product
      - customer
      - reservation
      - rabbitmq
    environment:
      PYTHONUNBUFFERED: 1
      product_manager_URL: http://localhost:5001/product
      inventory_manager_URL: http://localhost:5002/inventory
    ports:
      - "5000:5000"

  ###################################
  # Payment: The Payment microservice
  ###################################
  # payment:
  #   build:
  #     context: ./
  #     dockerfile: payment.Dockerfile
  #   image: wenhai87/payment:esd
  #   restart: always
  #   environment:
  #     PYTHONUNBUFFERED: 1

  ###################################
  # Notification: The Notification microservice
  ###################################
  # notification:
  #   build:
  #     context: ./
  #     dockerfile: notification.Dockerfile
  #   image: wenhai87/notification:esd
  #   restart: always
  #   environment:
  #     PYTHONUNBUFFERED: 1

  ###################################
  # Inventory: The Inventory microservice
  ###################################
  inventory:
    build:
      context: ./
      dockerfile: inventory.Dockerfile
    image: wenhai87/inventory:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/inventory_manager
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"
  
  ###################################
  # Product: The Product microservice
  ###################################
  product:
    build:
      context: ./
      dockerfile: product.Dockerfile
    image: wenhai87/product:esd
    restart: always
    environment:
      dbURL:  mysql+mysqlconnector://is213@host.docker.internal:3306/product_manager
      PYTHONUNBUFFERED: 1

  ##################################
  # Customer: The Customer microservice
  ##################################
  customer:
    build:
      context: ./
      dockerfile: customer.Dockerfile
    image: wenhai87/customer:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/customer_manager
      PYTHONUNBUFFERED: 1

  ##################################
  # Reservation: The Reservation microservice
  ##################################
  reservation:
    build:
      context: ./
      dockerfile: reservation.Dockerfile
    image: wenhai87/reservation:esd
    restart: always
    environment:
      dbURL:  mysql+mysqlconnector://is213@host.docker.internal:3306/reservation_manager
      PYTHONUNBUFFERED: 1

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq